name: CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node_version: [12, 16]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}

      - name: npm install, build and test
        env:
          CONTENTFUL_INTEGRATION_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          CONTENTFUL_INTEGRATION_SOURCE_SPACE: ${{ secrets.CONTENTFUL_SPACE_ID }}
        run: |
          npm install
          npm run build
          npm run test:ci
